# Generated by Django 3.2.19 on 2023-07-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0003_objecttag__taxonomy"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenObjectTag",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("oel_tagging.objecttag",),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="_object_tag_class",
            field=models.CharField(
                help_text="Overrides the default BaseObjectTag subclass associated with this taxonomy.Must be a fully-qualified module and class name.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClosedObjectTag",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("oel_tagging.openobjecttag",),
        ),
    ]
