# Generated by Django 4.2.19 on 2025-03-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_publishing', '0003_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_publishing.container',),
        ),
        migrations.CreateModel(
            name='UnitVersion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_publishing.containerversion',),
        ),
    ]
