# Generated by Django 4.2.16 on 2024-10-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oel_containers.containerversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oel_containers.container')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
