# Generated by Django 4.2.19 on 2025-03-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_publishing', '0003_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oel_publishing.container')),
            ],
            options={
                'abstract': False,
            },
            bases=('oel_publishing.container',),
        ),
        migrations.CreateModel(
            name='UnitVersion',
            fields=[
                ('container_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oel_publishing.containerversion')),
            ],
            options={
                'abstract': False,
            },
            bases=('oel_publishing.containerversion',),
        ),
    ]
